export {default as TasksRegisterForm} from "./components/TasksRegisterForm"
export {default as TasksPage} from "./pages/TasksPage"
export {default as MyTasksPage} from "./pages/MyTasksPage"
export {default as TasksUpdateForm} from "./components/TaskUpdateForm"
export {default as TaskEvidenceCard} from "./components/TaskEvidenceCard"
export { submitTaskEvidence, confirmTask, getTasksPendingConfirmation } from "./services/taskService"